name: Build and Publish Docker Image
on:
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    publish:
        uses: DCC-BS/ci-workflows/.github/workflows/publish-docker.yml@10a3d20a08ce3a33ec11aa3fa97b16b83983288c # v10
        secrets: inherit
        with:
            project_type: "python" # or "node"
            registry: ghcr.io
            image_name: ghcr.io/${{ github.repository }}
            context: .
            dockerfile: ./Dockerfile
            platforms: linux/amd64
            push: true
            # build_args: PRELOAD_MODEL=false
